### ISSUE TITLE
example.com

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/tile-attribution#1]
This is an example issue for example.com. Example.com has been not been attributing OpenStreetMap.org while using our tiles.

- [ ] Criteria 1
- [x] Criteria 2
- [ ] Criteria 3
- [x] Criteria 4

I propose that we stop serving tiles to example.com because of their failure to attribute us despite being asked.

**Comment by abdullahO2** [comment]
@matkoniecz @Firefishy @tomhughes 
What if there were app developers supporting a team that took OSM maps, merged stolen maps with them, made minor modifications to them, then attributed them to them and sold them?

**Comment by grischard** [comment]
@abdullahO2 that would be covered by the share-alike clause of the ODbL. If you're interested in discussing this, I encourage you to post to https://community.openstreetmap.org - this is not the place where you will get a lot of replies.

**Comment by matkoniecz** [comment]
@abdullahO2 It would be out of scope if this specific repository, unless they would also use OSMF tile servers.

If you would encounter this case it is better to post about it on https://community.openstreetmap.org/ or write to LWG if situation is 100% clear.

**Comment by abdullahO2** [comment]
@matkoniecz @grischard Thank you very much
