### ISSUE TITLE
Provide script that calls Fastly CLI to rewrite dictionary with current contents of CSV

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/tile-attribution#13]
We need to start updating the `attribution_blocked_domains` dictionary with a shell script to avoid manual work. This script will need to call the fastly CLI.

As far as I can tell, this needs to be done by
1. calling [`fastly dictionary describe`](https://developer.fastly.com/reference/cli/dictionary/describe/) to get the dictionary ID
2. Get items with [`fastly dictionary-entry list`](https://developer.fastly.com/reference/cli/dictionary-entry/list/)
3. Diff the items against the CSV file
4. Add any missing, and remove any that have been removed.

It is important that it does not rewrite the entire dictionary contents, as that will remove the date added information which is useful.

See also https://developer.fastly.com/learning/concepts/edge-state/dynamic-config/#edge-dictionaries

**Comment by Firefishy** [comment]
Rather please move to using [terraform-fastly](https://github.com/openstreetmap/terraform-fastly/). Terraform can read the CSV file direct from github if neccessary.

**Comment by Firefishy** [comment]
https://registry.terraform.io/providers/fastly/fastly/latest/docs/resources/service_dictionary_items

**Comment by pnorman** [comment]
We don't have terraform ready to go, and no ETA on when it will be ready.

**Comment by Firefishy** [comment]
> We don't have terraform ready to go, and no ETA on when it will be ready.

I've literally posted the only terraform code that is required above. I've now even made the job easier by publishing JSON which can be used directly by terraform HCL: https://raw.githubusercontent.com/openstreetmap/tile-attribution/main/tile-attribution.json

**Comment by Firefishy** [comment]
Fully working code:

```
terraform {

  required_version = "~> 1.5.6"

  required_providers {
    fastly = {
      source  = "fastly/fastly"
      version = ">= 5.4.0"
    }
  }
}

# Configure the Fastly Provider
# Use export FASTLY_API_KEY="afastlyapikey" terraform plan
provider "fastly" {}

data "http" "tile_attribution_data" {
  url = "https://raw.githubusercontent.com/openstreetmap/tile-attribution/main/tile-attribution.json"
}

import {
    id = "3vqMSxvFYqyVOoTY8ti37P/1EMhjtZi0Mwq5ZcSElM5Gs"
    to = fastly_service_dictionary_items.attribution_blocked_domains
}

resource "fastly_service_dictionary_items" "attribution_blocked_domains" {
  dictionary_id = "1EMhjtZi0Mwq5ZcSElM5Gs"
  items = jsondecode(data.http.tile_attribution_data.response_body)
  manage_items = true
  service_id   = "3vqMSxvFYqyVOoTY8ti37P"
}
```
