### ISSUE TITLE
https://www.idf.il/ar/ gaza map to evacuate zones

### ISSUE THREAD

**Issue by pierzen** [openstreetmap/tile-attribution#16]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [ ] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

![image](https://github.com/openstreetmap/tile-attribution/assets/680008/33966cb9-7b29-443b-9e4f-d0c2911cc82f)

### Where it is happening?

This is about OSM map tile services used in the context of a war in a way that people may question osm iinvolvment even if indirect since casualties reported in so called «safe zones», plus with no appropriate osm attribution.  

I would let OSMF decide to either send a love letter or block the url. 

As reported by France24, 
Since the resumption of the Israeli offensive on the north and south of the Gaza Strip on December 1, the armed forces have regularly dropped leaflets and contacted Palestinian civilians, calling on them to evacuate to what they call " safe areas" in the south of the Gaza Strip. But images filmed on the ground show that some of these areas have been bombed several times.  A QR code points to [www.idf.il/ar gaza map](https://www.idf.il/ar/%d8%ac%d9%8a%d8%b4-%d8%a7%d9%84%d8%af%d9%81%d8%a7%d8%b9-%d8%a7%d9%84%d8%a5%d8%b3%d8%b1%d8%a7%d8%a6%d9%8a%d9%84%d9%8a/%d8%ac%d9%8a%d8%b4-%d8%a7%d9%84%d8%af%d9%81%d8%a7%d8%b9-%d8%a7%d9%84%d8%a5%d8%b3%d8%b1%d8%a7%d8%a6%d9%8a%d9%84%d9%8a/swordsofiron-011223-150/) with OSM as background map and https://a.tile.openstreetmap.org as tile server.
see 
EN: https://observers-france24-com.translate.goog/fr/moyen-orient/20231220-sud-gaza-armee-israelienne-tracts-evacuer-bombarde-zones-sures-civils?_x_tr_sl=fr&_x_tr_tl=en&_x_tr_hl=fr&_x_tr_pto=wapp
FR: https://observers.france24.com/fr/moyen-orient/20231220-sud-gaza-armee-israelienne-tracts-evacuer-bombarde-zones-sures-civils

**Comment by Firefishy** [comment]
This isn't an easy one... I would not be comfortable blocking a service used to advise civilians on evacuation.

**Comment by matkoniecz** [comment]
Also, effects about being attributed there, as required by our license, may have some unwanted consequences.

Especially if evacuation advise there would turn out to be misleading with areas described as safe being bombed.

**Comment by matkoniecz** [comment]
In this specific situation I would likely avoid doing anything and close this issue, but I am not fully sure.

See also https://community.openstreetmap.org/t/usage-of-the-osm-tile-server-in-the-context-of-a-war-plus-no-osm-attribution/107321

**Comment by matkoniecz** [comment]
I think I will close it due to relatively small negative effects of ongoing situation (where they violate OSM license) and potential for massive trouble if we get involved into this specific conflict and things will go wrong.

And they can easily go wrong in multiple ways.

------------------

@pierzen You are highly welcome to report other sites using OSMF servers and having such problem. But this one is one big trap and in this game not playing seems the winning move.

> I would let OSMF decide to either send a love letter or block the url.

Thanks for doing this.
