### ISSUE TITLE
www.privateinternetaccess.com

### ISSUE THREAD

**Issue by jmarchon1** [openstreetmap/tile-attribution#19]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [X] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### Date and time of the message (has it happened more than a week ago?):

December 16, 2023 (~2 weeks ago)

### Where did you send it?

I used the "Submit a Ticket" form on their website.

### Please paste the content of the Love Letter you sent to the map user here.

Hello,

We OpenStreetMap contributors are very proud to see that you are using our work at https://www.privateinternetaccess.com/what-is-my-ip. Many people and systems, including your website would not be possible without the project’s data

OpenStreetMap owes its success to our millions of volunteers who share our vision and invest their time to maintain and improve the data. Many became contributors after starting as users. While most OSM-based maps are independently deployed, operators recognise the benefit of highlighting their use of OpenStreetMap. We believe end users realise that they can improve their experience by improving the map data. Thus, there are compelling reasons to attribute OpenStreetMap, even beyond the legal obligation. Unfortunately https://www.privateinternetaccess.com/what-is-my-ip does not provide this required attribution

You use our data in the maps displayed at https://www.privateinternetaccess.com/what-is-my-ip. We are happy to see our data used, and we hope uses such as yours can help attract more contributors to the map.

We very much regret that the obligatory attribution of OpenStreetMap is missing from your website. Just as you would credit a photographer when using his or her images, you are required to do the same when you use OpenStreetMap data. Our licence, although “Free and Open” carries a small number of conditions, one of which is the requirement to provide correct attribution.

We are sure that you will recognise the importance of rectifying this oversight and bringing your website into compliance with the licence under which our data is made available to you. Remember, not only is this a legal condition of your use of OSM, it also respects the volunteers who made your map and it helps encourage your users to improve it. Full details on how to attribute OpenStreetMap can be found in the Attribution Guidelines at https://osmfoundation.org/wiki/Licence/Attribution_Guidelines.

Acknowledgement of receipt would be appreciated.

Thanks,

jmarchon

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

![image](https://github.com/openstreetmap/tile-attribution/assets/50030493/2bd854fc-537c-4b8a-95da-1e0f9a7ec205)

### Where it is happening?

https://www.privateinternetaccess.com/what-is-my-ip

**Comment by jmarchon1** [comment]
I received a reply to my ticket on the same day I submitted it saying that they had "escalated your ticket to the appropriate team". Nothing appears to have happened in the 2 weeks since.

**Comment by matkoniecz** [comment]
@jmarchon1 Thanks! Note that there is some delay between blocking/unblocking here results in some changes visible on the website.

**Comment by jmarchon1** [comment]
That was fast, thank you! Does this mean their usage has been blocked? If so, I would send them a follow up email notifying of such.

**Comment by matkoniecz** [comment]
> Does this mean their usage has been blocked?

https://github.com/openstreetmap/tile-attribution/commit/93635928709ac37a1fe450e9fa655ff9327aad29 was triggered what should result in CDN delivering tiles being instructed to stop delivering tiles there (in summary)

it will take some time to propagate, about 24h

> If so, I would send them a follow up email notifying of such.]

I would wait for block resulting in changes (and keep such mail polite!)

**Comment by jmarchon1** [comment]
It has been well over 24 hours now and the tiles appear to still load fine. Is that normal? I'm probably just too impatient :-)

**Comment by Firefishy** [comment]
Change is live now.

**Comment by jmarchon1** [comment]
They finally replied a few hours ago:
"Hi Jmarchon,
 
This is Atlas from the Private Internet Access Support escalations.
 
I am reaching out to offer a sincere apology for the delay in responding to your question from a few months back. We take full responsibility for not addressing your concerns promptly.
 
We understand that there are no excuses for the communication breakdown, and we are truly disappointed that we did not provide the excellent service we aim for. We are currently investigating to identify this issue's root cause and prevent its recurrence.
 
To give you an update, we are working on adding the requested attribution. Please let us know if there is anything else you wish to add since the last time we spoke.
 
We hope that this experience will not alter your opinion of the VPN. We are dedicated to delivering the best service and are working hard to address our shortcomings.
 
I'll be on the lookout for your response. Thank you for your understanding.
 
Best regards,
Atlas
Private Internet Access Support"

**Comment by Firefishy** [comment]
I have now removed the "accepted" tag in good faith they will make the fix.
