### ISSUE TITLE
saverudata.info

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/tile-attribution#3]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [ ] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### The infringement is a:

- [ ] website
- [ ] app or other

**Comment by Firefishy** [comment]
As of November 2023 blocked from tile.openstreetmap.org due to missing attrribution.

**Comment by matkoniecz** [comment]
@Firefishy Do you have any notes/idea where OSM data was used on this website?

It is also not on https://wiki.openstreetmap.org/wiki/Lacking_proper_attribution or https://wiki.openstreetmap.org/wiki/Lacking_proper_attribution/Fixed

**Comment by Firefishy** [comment]
It was blocked by tile.openstreetmap.org code awhile back, likely out of date now.
