### ISSUE TITLE
www.netz-leipzig.de

### ISSUE THREAD

**Issue by mapl** [openstreetmap/tile-attribution#31]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [X] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### Date and time of the message (has it happened more than a week ago?):

Date: Mon, 22 Jan 2024 12:00:00+0100

### Where did you send it?

info@netz-leipzig.de

### Please paste the content of the Love Letter you sent to the map user here.

Liebe Netz Leipzig GmbH,

wir OpenStreetMap-Mitarbeiter sind sehr stolz darauf, dass Sie unsere
unsere Arbeit unter ["https://www.netz-leipzig.de/service/anschlussmoeglichkeiten"](https://www.netz-leipzig.de/service/anschlussmoeglichkeiten) nutzen.
Viele Menschen und Systeme, darunter auch Ihre Nutzung als Standortkarte, wären
ohne die Daten des Projekts nicht möglich. In der Tat ist es das Ziel des OpenStreetMap
Projekt hat sich zum Ziel gesetzt, die besten Daten für genaue und
lesbare Hintergrundkarten. OpenStreetMap verdankt seinen Erfolg den Millionen
von Freiwilligen, die unsere Vision teilen und ihre Zeit investieren, um die Daten zu
und die Daten zu verbessern. Viele wurden zu Mitwirkenden, nachdem sie als Nutzer angefangen hatten.
Die meisten OSM-basierten Karten werden zwar unabhängig bereitgestellt, aber die Betreiber
erkennen die Betreiber den Vorteil, ihre Nutzung von OpenStreetMap hervorzuheben. Wir
glauben, dass die Endnutzer erkennen, dass sie ihre Erfahrungen verbessern können, indem sie
Verbesserung der Kartendaten. Es gibt also zwingende Gründe, die Attribution von
OpenStreetMap zu nennen, auch über die gesetzliche Verpflichtung hinaus. Leider
bietet https://www.netz-leipzig.de/service/anschlussmoeglichkeiten nicht
diese erforderliche Namensnennung nicht.

Sie verwenden unsere Daten in den Karten, die unter
https://www.netz-leipzig.de/service/anschlussmoeglichkeiten. Wir sind froh
dass unsere Daten verwendet werden, und wir hoffen, dass Verwendungen wie die Ihre dazu beitragen können
mehr Mitwirkende für die Karte zu gewinnen. Wir bedauern sehr, dass die obligatorische
Namensnennung von OpenStreetMap auf Ihren Karten fehlt. Genauso wie Sie
einen Fotografen bei der Verwendung seiner Bilder nennen würden, sind Sie
müssen Sie das auch tun, wenn Sie OpenStreetMap-Daten verwenden. Unsere Lizenz,
obwohl sie "frei und offen" ist, enthält eine kleine Anzahl von Bedingungen, von denen eine
eine davon ist die Forderung nach korrekter Namensnennung. Wie in
unseren Richtlinien zur Namensnennung (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines) kann die
kann die Namensnennung in einer Ecke der Karte erscheinen. Während die untere rechte Ecke
ist traditionell, aber jede Ecke der Karte ist akzeptabel. Alternativ dazu kann die
neben der Karte oder auf einem Begrüßungsbildschirm oder einem
Pop-up, das beim Start der App, des Geräts, der Website usw. angezeigt wird. Wir sind
sind sicher, dass Sie erkennen, wie wichtig es ist, dieses Versäumnis zu korrigieren
Versehen zu korrigieren und https://www.netz-leipzig.de/service/anschlussmoeglichkeiten
in Einklang mit der Lizenz zu bringen, unter der Ihnen unsere Daten zur Verfügung gestellt werden.
Denken Sie daran, dass dies nicht nur eine rechtliche Bedingung für Ihre Nutzung von OSM ist, sondern
es respektiert auch die Freiwilligen, die Ihre Karte erstellt haben, und es hilft den
Ihre Nutzer zu ermutigen, sie zu verbessern. Ausführliche Informationen über die Attributierung von
OpenStreetMap finden Sie in den Richtlinien zur Namensnennung.

[ENGLISH]
Dear Netz Leipzig GmbH,

We OpenStreetMap contributors are very proud to see that you are using
our work at ["https://www.netz-leipzig.de/service/anschlussmoeglichkeiten"](https://www.netz-leipzig.de/service/anschlussmoeglichkeiten).

Many people and systems, including your use as a locator map, would not
be possible without the project’s data. Indeed, the OpenStreetMap
project’s goal is to freely provide the best data for accurate and
readable background maps. OpenStreetMap owes its success to our millions
of volunteers who share our vision and invest their time to maintain
and improve the data. Many became contributors after starting as users.
While most OSM-based maps are independently deployed, operators
recognise the benefit of highlighting their use of OpenStreetMap. We
believe end users realize that they can improve their experience by
improving the map data. Thus, there are compelling reasons to attribute
OpenStreetMap, even beyond the legal obligation. Unfortunately
https://www.netz-leipzig.de/service/anschlussmoeglichkeiten does not provide
this required attribution.

You use our data in the maps displayed at
https://www.netz-leipzig.de/service/anschlussmoeglichkeiten. We are happy
to see our data used, and we hope uses such as yours, can help attract
more contributors to the map. We very much regret that the obligatory
attribution of OpenStreetMap is missing from your maps. Just as you
would credit a photographer when using his or her images, you are
required to do the same when you use OpenStreetMap data. Our licence,
although “Free and Open” carries a small number of conditions, one of
which is the requirement to provide correct attribution. As noted in
our Attribution Guidelines (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines) the
credit can appear in a corner of the map. While the lower right corner
is traditional, any corner of the map is acceptable. Alternatively, the
attribution may be placed adjacent to the map or on a splash screen or
pop-up shown when a user starts the app, device, website, etc. We are
sure that you will recognise the importance of rectifying this
oversight and bringing https://www.netz-leipzig.de/service/anschlussmoeglichkeiten
into compliance with the licence under which our data is made available to you.
Remember, not only is this a legal condition of your use of OSM, it
also respects the volunteers who made your map and it helps encourage
your users to improve it. Full details on how to attribute
OpenStreetMap can be found in the Attribution Guidelines.

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

![image](https://github.com/openstreetmap/tile-attribution/assets/9784732/e7e6c1d4-7328-4b1c-a925-8d07efcebc3b)

### Where it is happening?

https://www.netz-leipzig.de/service/anschlussmoeglichkeiten

**Comment by matkoniecz** [comment]
So now it is waiting for someone to contact them using https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates

@mapl - are you planning to do this?

**Comment by mapl** [comment]
I've contacted them and updated the issue template.
[Next Steps]
Waiting for Response

**Comment by Firefishy** [comment]
Note we can only block full domains eg: `www.netz-leipzig.de` and the URL portion eg: `/service/anschlussmoeglichkeiten` should be removed.

**Comment by mapl** [comment]
They provide another OSM Map on a subpage with proper tile attribution. https://www.netz-leipzig.de/service/stoerungskarte/
This would then probably also be blocked.

**Comment by Firefishy** [comment]
@matkoniecz Please only accept ticket if domain is stripped raw domain. Alternatively the CI code needs updates.
