### ISSUE TITLE
Can we reduce dependabot volume?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/tile-attribution#33]
Getting repeated rubocop PRs due to some far away dependency seems not very useful. See https://github.com/openstreetmap/tile-attribution/pulls?q=is%3Apr+author%3Aapp%2Fdependabot

See say https://github.com/openstreetmap/tile-attribution/pull/32

Can we reduce how often we get this updates? Or even get rid of rubocop in its entirety?

Or set them to be merged automatically? 

Or maybe I should block @dependabot so I will not get notifications? (it appears to be impossible)

**Comment by Firefishy** [comment]
Changed it to weekly updates.

**Comment by matkoniecz** [comment]
was done in https://github.com/openstreetmap/tile-attribution/commit/bdae00a02ae040a70b8ec2266760cc54f750ef16
