### ISSUE TITLE
www.villesavivre.fr

### ISSUE THREAD

**Issue by peclet1248** [openstreetmap/tile-attribution#39]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [X] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### Date and time of the message (has it happened more than a week ago?):

20/03/2024

### Where did you send it?

contact@villesavivre.fr

### Please paste the content of the Love Letter you sent to the map user here.

Dear villesavivre.fr

We OpenStreetMap contributors are very proud to see that you are using
our work at "villesavivre.fr".

Many people and systems, including your use as a locator map, would not
be possible without the project’s data. Indeed, the OpenStreetMap
project’s goal is to freely provide the best data for accurate and
readable background maps. OpenStreetMap owes its success to our millions
of volunteers who share our vision and invest their time to maintain
and improve the data. Many became contributors after starting as users.
While most OSM-based maps are independently deployed, operators
recognise the benefit of highlighting their use of OpenStreetMap. We
believe end users realize that they can improve their experience by
improving the map data. Thus, there are compelling reasons to attribute
OpenStreetMap, even beyond the legal obligation. Unfortunately
https://www.villesavivre.fr/ does not provide
this required attribution.

You use our data in the maps displayed at
https://www.villesavivre.fr/romille-35245/#reviews. We are happy
to see our data used, and we hope uses such as yours, can help attract
more contributors to the map. We very much regret that the obligatory
attribution of OpenStreetMap is missing from your maps. Just as you
would credit a photographer when using his or her images, you are
required to do the same when you use OpenStreetMap data. Our licence,
although “Free and Open” carries a small number of conditions, one of
which is the requirement to provide correct attribution. As noted in
our Attribution Guidelines (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines) the
credit can appear in a corner of the map. While the lower right corner
is traditional, any corner of the map is acceptable. Alternatively, the
attribution may be placed adjacent to the map or on a splash screen or
pop-up shown when a user starts the app, device, website, etc. We are
sure that you will recognise the importance of rectifying this
oversight and bringing https://www.villesavivre.fr/
into compliance with the licence under which our data is made available to you.
Remember, not only is this a legal condition of your use of OSM, it
also respects the volunteers who made your map and it helps encourage
your users to improve it. Full details on how to attribute
OpenStreetMap can be found in the Attribution Guidelines.

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

![Screenshot 2024-03-20 at 09 37 26](https://github.com/openstreetmap/tile-attribution/assets/162812488/ff161c2a-bb93-400d-b4bb-ec85e4fce413)

### Where it is happening?

https://www.villesavivre.fr/romille-35245/#reviews

And all website pages

**Comment by peclet1248** [comment]
Still no response and no attribution on the website

![Screenshot 2024-03-27 at 08 56 48](https://github.com/openstreetmap/tile-attribution/assets/162812488/8584ecde-6cf3-4ea9-883c-8658f23c8aa6)

**Comment by Firefishy** [comment]
Confirmed blocked.

**Comment by peclet1248** [comment]
Just receive an email from the developer of this website:

> Hello,
> 
> We are sorry for this bad integration. We just added attribution to OSM contributors on all our leaflet maps.
> Thank you.
> 
> Best regards
> 
> Jean-Baptiste
> https://www.villesavivre.fr/

This again prove that a block might wake up a developer ;) Don't know if it's possible to give a time penalty for this. For example a ban generate a minimum block of one week even the website add the attribution. For example in this case the developer doesn't answer to the email for 8 days and when he saw what osm can do, he add the missing attribution and osm re-autorize the tiles 8 (time during ban and new attribution) days after that...

**Comment by matkoniecz** [comment]
I would not be vindicative, achieving this kind of effect is goal of that project.

(though I am making no promises whatsoever that I will not be on say multiday bicycle trip when someone fixed attribution and there is no guarantee of prompt unblocking)

And it is better reaction than setting own tile server rather than adding legally required attribution.

**Comment by matkoniecz** [comment]
Note: unblocking may have some delay, like blocking has.
