### ISSUE TITLE
www.impresaitalia.info

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/tile-attribution#4]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [ ] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### The infringement is a:

- [x] website
- [ ] app or other

**Comment by Firefishy** [comment]
As of November 2023 blocked from tile.openstreetmap.org due to missing attribution.

**Comment by matkoniecz** [comment]
@Firefishy it seems that it does not use OSMF tiles or OSM data anywhere? I guess we should remove it?

Do you have any notes where OSMF hosted tiles were used?

**Comment by Firefishy** [comment]
Sure. Closing.

**Comment by matkoniecz** [comment]
https://github.com/openstreetmap/tile-attribution/issues/13#issuecomment-1842622175 implies that it was done on LWG request in 2022.

No idea should this block be maintained and is this repository proper place to store it.
