### ISSUE TITLE
lista-drillowcow.pl

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/tile-attribution#42]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [ ] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [X] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### Date and time of the message (has it happened more than a week ago?):

2024-04-08

### Where did you send it?

nowhere, Telegram channel of group threatening/doxing people is not a reasonable contact method

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

![screen](https://github.com/openstreetmap/tile-attribution/assets/899988/ffe143f2-a936-4f7d-bc9e-5b30f0c1c32c)

### Where it is happening?

https://lista-drillowcow.pl/

**Comment by grischard** [comment]
No reasonable contact method->block

**Comment by iam-py-test** [comment]
`lista-drillowcow.pl` seems to return NXDOMAIN (does not exist). Did they switch domains?
Thanks

**Comment by matkoniecz** [comment]
Maybe, if yes then please let us know about new one.
