### ISSUE TITLE
tools.usps.com

### ISSUE THREAD

**Issue by louwers** [openstreetmap/tile-attribution#49]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [X] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### Date and time of the message (has it happened more than a week ago?):

10th of May 16:24 CEST

### Where did you send it?

To their support https://www.usps.com/help/contact-us.htm

### Please paste the content of the Love Letter you sent to the map user here.

![image](https://github.com/openstreetmap/tile-attribution/assets/649392/2029d90e-0d29-4f84-878a-581d7d08933d)

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

<img width="2056" alt="Screenshot 2024-05-17 at 00 38 17" src="https://github.com/openstreetmap/tile-attribution/assets/649392/f3c300c4-50c5-4f9f-ade9-b014415b86a0">

### Where it is happening?

https://tools.usps.com/locations/home.htm

You need to enter a ZIP code (e.g. 10001).

**Comment by louwers** [comment]
I have sent another follow-up with a reminder.

**Comment by matkoniecz** [comment]
Thanks for reporting!

I am trying to reach out to them as serious government organization seems more likely to be persuaded than some fly-by-night company, and there may be some proper official way of contacting them more likely to result in some fix.

(from my experience with government in another country - they typically have some contact channels where contact will result in prompt response while "contact us" forms at their websites often go straight into trash.

So I will not apply block right now, but I will do this if new efforts will fail.

**Comment by louwers** [comment]
Maybe we can abuse their vulnerability disclosure programme: https://hackerone.com/usps

**Comment by matkoniecz** [comment]
I attempted to contact them via their website (refuses to work without US address) and through https://www.facebook.com/USPS (refused to work outside US working hours, will retry)

**Comment by matkoniecz** [comment]
> After review, there doesn’t seem to be any significant security risk and/or security impact as a result of the behavior you are describing.

Well, it was longshot. I guess that degradation of features (blocking map tiles) is not exactly a security risk.

**Comment by louwers** [comment]
I will give a call to their technical support today during US business hours.

If that doesn't work, we should probably give up.

**Comment by matkoniecz** [comment]
I may try writing on US forum whether anyone has idea how to contact them (or maybe we will be lucky and get USPS employee).

**Comment by matkoniecz** [comment]
Found their email and posted it there.

**Comment by Melaskia** [comment]
Hello,

I asked a friend of mine at USPS about that. The website is its own entity
different from the day to day operation of USPS. Even him had no clear idea
on how to reach the website people.

**Comment by louwers** [comment]
The technical support phone number also does not cover USPS Tools.

**Comment by matkoniecz** [comment]
I reported it yesterday via mail, got promise of response within 48 hours.

Tracking number: ref:!00Dj00GyYH.!500BY02LFVT:ref

**Comment by louwers** [comment]
I never got a reply, maybe you will have more luck.

**Comment by gregorywaynepower** [comment]
Perhaps you could reach out to the folks at [Medallia](https://www.medallia.com/) that build this application?

**Comment by louwers** [comment]
It's been 14 days since I sent my message, and 7 days since I sent this reminder.

**Comment by b1tw153** [comment]
@watmildon and I would like to take a pass at making the right connections with USPS. You know how generic tech support e-mail can be. We'll try to get in touch with them starting on Tuesday because of the US holiday on Monday.

If you can afford more time before cutting them off from the tile server, that would be great. However, I understand if their usage is too much of a burden to allow it to continue. If we need to cut them off, I'd just like to know so we can include that in our communication.

**Comment by grischard** [comment]
Reasonable attempts have been made at contacting the USPS. Marking this one as accepted.

**Comment by grischard** [comment]
If anyone has a better contact at USPS, that would be very welcome.

**Comment by louwers** [comment]
@grischard Stop.

**Comment by grischard** [comment]
Yes, only issues that are open create an active block. You did the right thing!

**Comment by louwers** [comment]
Good thing the accepted label is removed though, otherwise I would have too much power.

**Comment by grischard** [comment]
Ah, the 'accepted' label can stay, this was a valid issue, although the point is moot now.

The [code](https://github.com/openstreetmap/tile-attribution/blob/369f15f5d8ba0044762cf1e77baf8700249f88f1/bin/update-issues#L57C1-L58C1) filters for issues that are both open and 'accepted'.

**Comment by louwers** [comment]
I think I could block them by re-opening the issue then.
