### ISSUE TITLE
www.rifugi.lombardia.it

### ISSUE THREAD

**Issue by alexanderzatko** [openstreetmap/tile-attribution#51]
https://www.rifugi.lombardia.it/sondrio/val-masino/rifugio-gianetti.html

steps to reproduce

1. go to a refugio page, for example the one given above
2. click the SCOPRI thingy in the right lower corner to switch the photo in the frame for a map
3. click OpenStreetMap item in the layer switcher in the upper left corner of the map

Note: The [Contributing guidelines](https://github.com/openstreetmap/tile-attribution/blob/3df50e4dc7a97b691aac7b7b892827f7e299c624/CONTRIBUTING.md) are not very helpful.

<img width="1355" alt="Screenshot 2024-05-25 at 08 12 50" src="https://github.com/openstreetmap/tile-attribution/assets/3430677/ac6250c7-8c55-437d-8202-0485bca5d7b3">

**Comment by matkoniecz** [comment]
> Note: The [Contributing guidelines](https://github.com/openstreetmap/tile-attribution/blob/3df50e4dc7a97b691aac7b7b892827f7e299c624/CONTRIBUTING.md) are not very helpful.

What about a new version? See https://github.com/openstreetmap/tile-attribution/blob/668778e6d514813317dd97ab810c594a8d667f09/CONTRIBUTING.md

Do you plan to submit such request as described there?

**Comment by alexanderzatko** [comment]
I did not and do not plan to do this:

"You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added."

I will not do it in this case or any other I will encounter in the future. Does it mean that I can not use this (github) tool to manage cases of (suspected) violations for reporting?

**Comment by matkoniecz** [comment]
Yes. In such case it is better to add such entry to https://wiki.openstreetmap.org/w/index.php?title=Insufficient_attribution and note they use OSMF tile server. I actively monitor this page (see its history) and reported some here in this repository.

If you do not want it either - please add them to thread at official OSM forums about missing attributions.

**Comment by matkoniecz** [comment]
Unless someone else will pick this case up? I guess that single issue with https://github.com/openstreetmap/tile-attribution/labels/waiting%20for%20contact%20using%20specific%20template is fine? Lets see is there interest in processing it (strictly speaking I am interested but I have limited time)

**Comment by alexanderzatko** [comment]
Just to be clear, I plan to contact the violator, but not using the "love letter approach", as I consider it a failure to enforce the attribution requirement efficiently, and do so at a scale (as history can attest). You might be aware of my recent post to the osm-legal forum, where I outlined an alternative approach, which I intend to follow.

Regardless, I consider it important to have a common attribution violation tracking database for all types of violations, not only cases where the violator uses the osm tiles. Currently we have this Github-based and the Wiki-based general databases I am aware of and (I suspect) a number of regional ones like [the one the Slovak community has been using](https://github.com/FreemapSlovakia/freemap-operations/issues) for example. Ideally we would have just one, to avoid duplicating of cases resolution efforts.

**Comment by matkoniecz** [comment]
I would expect https://wiki.openstreetmap.org/w/index.php?title=Insufficient_attribution to be central one.

(Wiki editing can be a barrier, but demanding account at Microsoft managed service is also far from ideal, gitlab has atrocious interface etc - though ideas for better repository is welcome)

> this Github-based

It is not intended to replace or duplicate https://wiki.openstreetmap.org/w/index.php?title=Insufficient_attribution listing - it is intended only for cases qualifying for immediate termination of access to OSMF tile servers.

> I consider it a failure to enforce the attribution requirement efficiently

I agree. I have spend quite a lot of time to improve situation in this area (and this repository is one of effects - and to be clear many others also spend a lot of effort here, for start @grischard and @Firefishy ).

> You might be aware of my recent post to the osm-legal forum, where I outlined an alternative approach, which I intend to follow.

I have seen the title in my mailing list inbox, I have not seen its contents yet.

**Comment by matkoniecz** [comment]
either way, in this case you need to manually enable "OpenStreetMap" button, right? So main thing missing is mention of ODBL (and suppressing Google logo).


Either way it is not blatant and completely missing attribution

**Comment by alexanderzatko** [comment]
yes on all counts. However, it still takes our time to deal with the issue, which from my point of view warrants a compensation to us (which is the core point of the proposal I announced in the legal-talk forum).

**Comment by grischard** [comment]
Closing as stale, letter never sent
