### ISSUE TITLE
www.notaires.fr

### ISSUE THREAD

**Issue by cquest** [openstreetmap/tile-attribution#59]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [X] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### Please paste the content of the Love Letter you sent to the map user here.

see https://github.com/osm-fr/attributions/issues/457

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

![Capture d’écran du 2024-07-29 12-49-12](https://github.com/user-attachments/assets/bf1c0e38-7892-49bc-8d77-16e3c6e654f4)

### Where it is happening?

https://www.notaires.fr/fr/office/nicolle-et-associes

**Comment by matkoniecz** [comment]
Can you post content of message that was send to them?

**Comment by grischard** [comment]
@cquest since you say that you've contacted them, and it's been since June, I'll block them for now.

**Comment by atchisson** [comment]
> Can you post content of message that was send to them?

Hi, here is what i sent them : 

<details>
  <summary>In french</summary>
Bonjour,

En tant que cartographe OpenStreetMap, ça me fait plaisir de voir que vous utilisez une carte issue d'OpenStreetMap sur votre site.

Cependant, j'ai noté que la carte présente sur les pages de type "office" (par exemple : https://www.notaires.fr/fr/office/nicolle-et-associes) n'est pas correctement attribuée. En effet, nous demandons que votre crédit comporte la mention « © les contributeurs d’OpenStreetMap ». Vous devez également préciser clairement que les données sont disponibles sous la licence ODbL. Vous pouvez mentionner ceci avec un lien hypertexte vers https://www.openstreetmap.org/copyright.

Cela ressemble à un oubli, d'autant plus que les pages de type "département" (https://www.notaires.fr/fr/annuaire/provence-alpes-cote-dazur) sont bien attribuées.

Une attribution correcte permet de préciser les sources de la carte ou des données ainsi que ce que les utilisateurs ont le droit d'en faire.

Si vous n'êtes pas directement charge de la conception de ce site, vous pouvez transférer ce courriel au service ou à l'agence concernée. Si vous avez besoin d'aide pour effectuer la correction ou si vous avez des questions, ne pas hésiter à répondre à ce message ou à utiliser un de nos canaux de communication : https://wiki.openstreetmap.org/wiki/FR:Canaux_de_contact.

Enfin, une attribution correcte permet de diffuser l'existence d'OpenStreetMap, d'attirer de nouvelles contributions et d'étendre la communauté. C'est extrêmement important pour améliorer la qualité de la base de données en qui vous et des millions de personnes font confiance.

Lorsque la correction aura été faite, n'hésitez pas à me le signaler.

Merci d'avance !

Cordialement
</details>


<details>
  <summary>Translated with DeepL</summary>
Hello,

As an OpenStreetMap cartographer, I'm pleased to see that you're using an OpenStreetMap map on your site.

However, I've noticed that the map on the “office” pages (for example: https://www.notaires.fr/fr/office/nicolle-et-associes) is not correctly attributed. Indeed, we ask that your credit includes the mention “© OpenStreetMap contributors”. You must also clearly state that the data is available under the ODbL license. You can mention this with a hyperlink to https://www.openstreetmap.org/copyright.

This looks like an oversight, especially as the “department” pages (https://www.notaires.fr/fr/annuaire/provence-alpes-cote-dazur) are well attributed.

Correct attribution makes it possible to specify the sources of the map or data and what users are allowed to do with it.

If you are not directly responsible for the design of this site, please forward this e-mail to the appropriate department or agency. If you need help making the correction or have any questions, please don't hesitate to reply to this message or use one of our communication channels: https://wiki.openstreetmap.org/wiki/FR:Canaux_de_contact.

Finally, correct attribution helps to spread the word about OpenStreetMap, attract new contributions and expand the community. This is extremely important for improving the quality of the database you and millions of other people trust.

When the correction has been made, please let me know.

Thanks in advance!

Sincerely
<details>

**Comment by atchisson** [comment]
They fixed it : 
![image](https://github.com/user-attachments/assets/11373c98-266c-4aec-85d5-c5ce1fd9f4a7)
