### ISSUE TITLE
https://www.danubeportal.com/

### ISSUE THREAD

**Issue by pl71** [openstreetmap/tile-attribution#69]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [ ] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### The infringement is a:

- [X] website
- [ ] app or other

**Comment by matkoniecz** [comment]
are you planning to contact them asking to provide attribution?

**Comment by pl71** [comment]
Probvably will do
 But I  have no experience in such requests.

**Comment by matkoniecz** [comment]
Sending email based on https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates should be enough

**Comment by matkoniecz** [comment]
BTW, I see 
![screen](https://github.com/user-attachments/assets/2f6be619-4f4e-46da-b376-0f102a39d84e)
in bottom right at https://www.danubeportal.com/

is it missing on mobile?

**Comment by matkoniecz** [comment]
I will close it as it appears that attribution is present.

If it is missing, please provide info where.

**Comment by grischard** [comment]
It's not visible on mobile either.
