### ISSUE TITLE
ephtracking.cdc.gov

### ISSUE THREAD

**Issue by elevenchars** [openstreetmap/tile-attribution#75]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [X] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [X] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### Date and time of the message (has it happened more than a week ago?):

October 19th, 2024

### Where did you send it?

trackingsupport@cdc.gov

### Please paste the content of the Love Letter you sent to the map user here.

Hello,

As an OpenStreetMap contributor, I am pleased to see that you are
using OpenStreetMap on your website:

https://ephtracking.cdc.gov/Applications/heatTracker/
https://ephtracking.cdc.gov/DataExplorer/

However, I noticed that the map seems to lack the proper credit.
OpenStreetMap's license requires that you both credit OpenStreetMap
and make users aware of the data license (by linking to our copyright
page). For more information, see:

https://www.openstreetmap.org/copyright

The correct attribution helps to avoid misunderstandings about the
source of the map or data, as well as what others are allowed to do
with it. If you need help making the changes or have further questions,
feel free to ask me in reply to this mail, or others in one of
OpenStreetMap's communication channels:

https://wiki.openstreetmap.org/wiki/Contact

More importantly, attribution helps us spread the word about
OpenStreetMap and attract new contributors and build the community.
This is incredibly important to improving the quality of the database
that you and millions of others rely on.

Acknowledgement of receipt would be appreciated.

Thanks,

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

![image](https://github.com/user-attachments/assets/ce333ca5-30db-4199-ad63-adcd5b4d981a)

![image](https://github.com/user-attachments/assets/b92f1631-b7c8-4a77-8535-cebbf2654ece)

### Where it is happening?

Dashboards hosted on https://ephtracking.cdc.gov/
Example dashboard:
https://ephtracking.cdc.gov/Applications/heatTracker/

### Previous Reports:

I previously contacted climateandhealth@cdc.gov on July 18th, 2024 with same template and did not receive a response.

**Comment by matkoniecz** [comment]
![screen02](https://github.com/user-attachments/assets/3aa9fd22-4761-40f6-9fac-82075057a411)

**Comment by matkoniecz** [comment]
Thanks for contacting them and reporting here!

Block once accepted may take up to 24 hours to apply.

**Comment by elevenchars** [comment]
I have now received a response from someone at the CDC. I directed them to the OSMF attribution guidelines, but they also said this:

> We do perform 4 builds a year where we can update to better attribute. The next build is in December. Please let me know if that will be sufficient as I do not have any way of changing code before then

**Comment by matkoniecz** [comment]
December is not far away let's give them a chance

**Comment by jayhawker6** [comment]
It would appear that it is currently down for maintenance. Hopefully attribution will be there when they come back up.

**Comment by jayhawker6** [comment]
@matkoniecz They are now using arcgis tileservers 
![image](https://github.com/user-attachments/assets/68f45948-362a-4a6c-a57b-59859bd2f625)
![image](https://github.com/user-attachments/assets/efe986e0-6246-4b4f-8b76-78f978657012)

**Comment by elevenchars** [comment]
The attribution is still missing on some pages (https://ephtracking.cdc.gov/Applications/heatTracker/ , for example) but I guess now this is outside the scope of this repository.

**Comment by matkoniecz** [comment]
Yes, we cannot just switch off their server access.

If they are not listed at https://wiki.openstreetmap.org/w/index.php?title=Insufficient_attribution they can be added there and I guess asking them again would make sense.

Contacting arcgis about using their servers for license violation also makes sense to me, but I have no big hopes about results there.
