### ISSUE TITLE
www.masecurite.interieur.gouv.fr

### ISSUE THREAD

**Issue by bmillemathias** [openstreetmap/tile-attribution#76]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [x] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### Date and time of the message (has it happened more than a week ago?):

Nov !st 2024

### Where did you send it?

https://www.masecurite.interieur.gouv.fr/fr/signalez-un-dysfonctionnement-technique

### Please paste the content of the Love Letter you sent to the map user here.

> Bonjour, je vous contacte en tant que contributeur OpenStreetMap.
>
> La page https://www.masecurite.interieur.gouv.fr/fr/trouver-un-commissariat-une-gendarmerie utilise notre fond de  > carte mais sans attribution. le formulaire n'ayante que 500 caractères je ne peux rentrer dans les détails, les indications
> pour corriger sont sur https://www.openstreetmap.org/copyright/fr
>
> Cordialement
>Baptiste Mille-Mathias

![image](https://github.com/user-attachments/assets/bd6c1c2a-5eb1-4ed3-ba11-35038cbf4e8e)

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

![image](https://github.com/user-attachments/assets/3d474616-cb04-4cb7-ad2e-6a173d0ed22c)

### Where it is happening?

https://www.masecurite.interieur.gouv.fr/fr/trouver-un-commissariat-une-gendarmerie

### Previous Reports:

no I did not find how contact webiste developers

**Comment by matkoniecz** [comment]
https://www.masecurite.interieur.gouv.fr/en/legal-information has at least one email

does not match exactly, but we can use it if they failed to provide better one

BTW, French police doing copyright violation is quite funny and sad.

**Comment by bmillemathias** [comment]
> https://www.masecurite.interieur.gouv.fr/en/legal-information has at least one email
> 
eventually I used https://www.masecurite.interieur.gouv.fr/fr/signalez-un-dysfonctionnement-technique to signal this, unfortunately it did not ask for personal information to follow the status and the length of the form is limited to 500 characters, so I had to keep it short.

> BTW, French police doing copyright violation is quite funny and sad.

Yes, and moreover that etalab (which contributes to OSM) collaborates on this website. 

Best

**Comment by Melaskia** [comment]
Hello,

have you tried reaching out to the French community? Some have connections
to Etatlab.

**Comment by matkoniecz** [comment]
@Melaskia I haven't done so, if you know people who may reach out to them - feel free to do so! Or link place where it can be done.

Note that it is entirely optional, using contact method they provided is entirely enough. If they failed to answer or provide proper one, it is not giving immunity from blocking.

**Comment by Melaskia** [comment]
Hello Mateusz,

I have not talked about immunity from blocking. There is a process and we
will follow it. I have 0 problem blocking an official website from the
French Interior ministry, which shows the location of various police
stations and so on.
I was just asking if we had reached out to the French community who might
have contact with the people behind the site, which could unblock the
situation since the form seems to be broken.

**Comment by matkoniecz** [comment]
@Firefishy 

it would need to be www.gouv.fr, right? Cab we block just some subdomain? (with title as is)

if it would be for entire www.gouv.fr it would be worth escalating first

**Comment by matkoniecz** [comment]
![screen05](https://github.com/user-attachments/assets/39cd373f-965a-4208-9cf9-325cf494ba9f)
looks fixed to me (not checked on mobile device as my phone died)

**Comment by Melaskia** [comment]
Hello,

Based on what I checked, it is indeed fixed.
Someone in the French community reached out to the people in charge of the
map, in addition to some other emails used.
