### ISSUE TITLE
www.perforce.com

### ISSUE THREAD

**Issue by jmarchon1** [openstreetmap/tile-attribution#8]
### Is it maybe reported already?

- [X] I have searched the existing issues, it is not reported already

### Before you submit this form, please ensure the following criteria are met:

- [X] The website/app in question uses map tiles hosted by the OpenStreetMap foundation (https://tile.openstreetmap.org).
- [X] The website/app does not have proper attribution. (https://osmfoundation.org/wiki/Licence/Attribution_Guidelines)
- [X] The usage of the tiles is non-trivial. (Not a development site, not test code, not a personal project with negligible traffic, etc.)
- [X] You have contacted the website/app owner or representative using the Love Letter model/template (https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates) more than a week ago and no proper attribution has been added.
- [ ] Or you have made a good faith effort to find working contact information for the website/app owner or representative but were unable to find a means to contact them.

### Date and time of the message (has it happened more than a week ago?):

2023-11-15, ~1.5 weeks ago

### Where did you send it?

info@perforce.com

### Please paste the content of the Love Letter you sent to the map user here.

Hello,

As an OpenStreetMap contributor, I am pleased to see that you are using OpenStreetMap for your website https://www.perforce.com/contact-us.

OSM is happy to see its data used, but its license requires that you both credit OpenStreetMap and make users aware of the data license (by linking to the copyright page). Unfortunately, your website does not provide this required attribution. For more information, see:

https://www.openstreetmap.org/copyright
https://osmfoundation.org/wiki/Licence/Attribution_Guidelines

If you need help making the changes or have further questions, feel free to ask me in reply to this mail, or others in one of OpenStreetMap's many communication channels:

https://wiki.openstreetmap.org/wiki/Contact

Acknowledgement of receipt would be appreciated.

Thanks,
jmarchon

### The infringement is a:

- [X] website
- [ ] app or other

### Please drag and drop or attach the screenshot showing the map without proper attribution here.

![image](https://github.com/openstreetmap/tile-attribution/assets/50030493/9b38036e-1a24-460c-8420-0842434ea3c7)

### Where it is happening?

https://www.perforce.com/contact-us

### Previous Reports:

None

**Comment by matkoniecz** [comment]
I guess the question is whether mail should match exactly https://osmfoundation.org/wiki/Licence/Attribution_Reminder_Templates template

**Comment by matkoniecz** [comment]
@jmarchon1 Can you send one extra email matching extended template?

(I did it with some entries I filed - mostly to keep anyone from making any legitimate complaints about this new process)

**Comment by jmarchon1** [comment]
The email I already sent followed another template from the wiki which I unfortunately can't find anymore. Should I still send another email using the template you linked?

**Comment by matkoniecz** [comment]
LWG published new recommended templates.

> Should I still send another email using the template you linked?

Yes, that is the new one.

**Comment by jmarchon1** [comment]
I've sent another email, as follows:
Dear Perforce,


We OpenStreetMap contributors are very proud to see that you are using our work at [www.perforce.com/contact-us](http://www.perforce.com/contact-us) . Many people and systems, including your website would not be possible without the project’s data

OpenStreetMap owes its success to our millions of volunteers who share our vision and invest their time to maintain and improve the data. Many became contributors after starting as users. While most OSM-based maps are independently deployed, operators recognise the benefit of highlighting their use of OpenStreetMap. We believe end users realise that they can improve their experience by improving the map data. Thus, there are compelling reasons to attribute OpenStreetMap, even beyond the legal obligation. Unfortunately [www.perforce.com/contact-us](http://www.perforce.com/contact-us) does not provide this required attribution


You use our data in the maps displayed at [www.perforce.com/contact-us](http://www.perforce.com/contact-us). We are happy to see our data used, and we hope uses such as yours can help attract more contributors to the map.


We very much regret that the obligatory attribution of OpenStreetMap is missing from your website. Just as you would credit a photographer when using his or her images, you are required to do the same when you use OpenStreetMap data. Our licence, although “Free and Open” carries a small number of conditions, one of which is the requirement to provide correct attribution.


We are sure that you will recognise the importance of rectifying this oversight and bringing your website into compliance with the licence under which our data is made available to you. Remember, not only is this a legal condition of your use of OSM, it also respects the volunteers who made your map and it helps encourage your users to improve it.   Full details on how to attribute OpenStreetMap can be found in the Attribution Guidelines at https://osmfoundation.org/wiki/Licence/Attribution_Guidelines.


Acknowledgement of receipt would be appreciated.


Thanks,

jmarchon

**Comment by p4jpieper** [comment]
Hello, 
I'm the web manager at Perforce. This was a definite oversight on our part and I apologize for the lack of attribution and for my delayed response. 

I've restored the attribution tile in the [lower right corner of this map](https://www.perforce.com/contact-us). Please let me know if any changes are required. 

![Contact_Us___Perforce](https://github.com/openstreetmap/tile-attribution/assets/66386011/44f1dc19-4646-4db3-b5ac-3f8d44f99bd6)

**Comment by Firefishy** [comment]
Thank you. Block removed. Allow upto 24 hours for the block to be fully removed.
